app_login/urls.py
from django.urls import path
from .views import login_view, logout_view, SignUpView

app_name = 'login'

urlpatterns = [
    path('', login_view, name="login_view"),
    path('logout/', logout_view, name="logout_view"),
    path('signup/', SignUpView.as_view(), name="signup_view"),
]

cart/urls.py
# urls.py in store

from django.urls import path
from .views import cart_view, cart_add_view, cart_del_view, cart_buy_now_view, cart_remove_view

app_name = 'cart'

urlpatterns = [
    path('', cart_view, name="cart_view"),
    path('add/<str:id_product>', cart_add_view),
    path('del/<str:id_product>', cart_del_view),
    path('buy/<str:id_product>', cart_buy_now_view, name="buy_now"),
    path('remove/<str:id_product>', cart_remove_view, name="remove_now"),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from random import random
from django.http import HttpResponse
from app_datetime.views import datetime_view
from project.settings import DEBUG


def random_view(request):
    if request.method == "GET":
        data = random()
        return HttpResponse(data)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('random/', random_view),
    path('datetime/', datetime_view),
    path('weather/', include('app_weather.urls')),
    path('', include('store.urls')),
    path('cart/', include('cart.urls')),
    path('login/', include('app_login.urls')),
    path('wishlist/', include('wishlist.urls')),
    path('auth/', include('social_django.urls', namespace='social')),
]

if DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

app_login/models.py
from django.db import models

# Create your models here.

app_login/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from django.contrib.auth.forms import UsernameField
from django.forms import EmailField


class CustomUserCreationForm(UserCreationForm):
   email = EmailField()

   class Meta:
       model = User
       fields = ['username', 'email', 'password1', 'password2']
       field_classes = {"username": UsernameField}

app_login/views.py
from django.contrib.auth import login, authenticate, logout
from django.shortcuts import render, redirect
from logic.services import add_user_to_cart, add_user_to_wishlist
from django.views import View
from .forms import CustomUserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm


def login_view(request):
    if request.method == "GET":
        return render(request, "login/login.html")

    if request.method == "POST":
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            add_user_to_cart(request, user.username)
            add_user_to_wishlist(request, user.username)
            return redirect("/")
        return render(request, "login/login.html", context={"error": "Неверные данные"})


def logout_view(request):
    if request.method == "GET":
        logout(request)
        return redirect("/")


class SignUpView(View):
    def get(self, request):
        return render(request, "login/signup.html")

    def post(self, request):
        form = CustomUserCreationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password1')
            user = User.objects.create_user(username=username, email=email,
                                            password=password)
            user.save()
            login(request, user, backend='django.contrib.auth.backends.ModelBackend')  # Авторизируем пользователя
            return redirect('/')
        return render(request, "login/signup.html",
                      context={'errors': form.errors})

app_login/templates/login/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login Form</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="{% static 'login/images/icons/favicon.ico"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/fonts/iconic/css/material-design-iconic-font.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/vendor/animate/animate.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'login/vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/vendor/animsition/css/animsition.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'login/vendor/daterangepicker/daterangepicker.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'login/css/main.css' %}">
<!--===============================================================================================-->
</head>
<body>
	
	<div class="limiter">
		<div class="container-login100" style="background-image: url({% static 'login/images/bg-01.jpg' %});">
			<div class="wrap-login100 p-l-55 p-r-55 p-t-65 p-b-54">
				<form action="." method="post" class="login100-form validate-form">
					{% csrf_token %}
					<span class="login100-form-title p-b-49">
						Авторизация
					</span>

					<div class="wrap-input100 validate-input m-b-23" data-validate = "Username обязателен">
						<span class="label-input100">Имя пользователя (username)</span>
						<input class="input100" type="text" name="username" placeholder="Введите свой username">
						<span class="focus-input100" data-symbol="&#xf206;"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="Пароль обязателен">
						<span class="label-input100">Пароль</span>
						<input class="input100" type="password" name="password" placeholder="Введите свой пароль">
						<span class="focus-input100" data-symbol="&#xf190;"></span>
					</div>
					
					<div class="text-right p-t-8 p-b-31">
						<a href="#">
							Забыли пароль?
						</a>
					</div>
					
					<div class="container-login100-form-btn">
						<div class="wrap-login100-form-btn">
							<div class="login100-form-bgbtn"></div>
							<button class="login100-form-btn">
								Авторизоваться
							</button>
						</div>
						{{error}}
					</div>

					<div class="txt1 text-center p-t-54 p-b-20">
						<span>
							Авторизоваться используя сторонние сервисы
						</span>
					</div>

					<div class="flex-c-m">
						<a href="#" class="login100-social-item bg1">
							<i class="fa fa-github"></i>
						</a>

						<a href="#" class="login100-social-item bg2">
							<i class="fa fa-vk"></i>
						</a>

						<a href="#" class="login100-social-item bg3">
							<i class="fa fa-google"></i>
						</a>
					</div>

					<div class="flex-col-c p-t-155">
					<span class="txt1 p-b-17">
						Не регистрировались ранее?
					</span>

					<a href="{% url 'login:signup_view' %}" class="txt2">
						Регистрация
					</a>
				</div>

				</form>
			</div>
		</div>
	</div>
	

	<div id="dropDownSelect1"></div>
	
<!--===============================================================================================-->
	<script src="{% static 'login/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'login/vendor/animsition/js/animsition.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'login/vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'login/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'login/vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'login/vendor/daterangepicker/moment.min.js' %}"></script>
	<script src="{% static 'login/vendor/daterangepicker/daterangepicker.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'login/vendor/countdowntime/countdowntime.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'login/js/main.js' %}"></script>

</body>
</html>

app_login/templates/login/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Sign Up Form</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="{% static 'login/images/icons/favicon.ico"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/fonts/iconic/css/material-design-iconic-font.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/vendor/animate/animate.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'login/vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/vendor/animsition/css/animsition.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'login/vendor/daterangepicker/daterangepicker.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'login/css/main.css' %}">
<!--===============================================================================================-->
</head>
<body>
	
	<div class="limiter">
		<div class="container-login100" style="background-image: url({% static 'login/images/bg-01.jpg' %});">
			<div class="wrap-login100 p-l-55 p-r-55 p-t-65 p-b-54">
				<form action="." method="post" class="login100-form validate-form">
					{% csrf_token %}
					<span class="login100-form-title p-b-49">
						Создать аккаунт
					</span>

					<div class="wrap-input100 validate-input m-b-23" data-validate = "Обязательное поле">
						<span class="label-input100">Имя пользователя (username)</span>
						<input class="input100" type="text" name="username" placeholder="Введите ваш username">
						<span class="focus-input100" data-symbol="&#xf206;"></span>
					</div>

					{% if errors.username%}
						<span class="txt1">
						  {{errors.username}}
						</span>
					{% endif %}

					<div class="wrap-input100 validate-input m-b-23" data-validate = "Обязательное поле">
						<span class="label-input100">Адрес электронной почты (email)</span>
						<input class="input100" type="text" name="email" placeholder="Введите ваш email">
						<span class="focus-input100" data-symbol="&#x2709;"></span>
					</div>

					{% if errors.email%}
						<span class="txt1">
						  {{errors.email}}
						</span>
					{% endif %}

					<div class="wrap-input100 validate-input" data-validate="Password is required">
						<span class="label-input100">Пароль</span>
						<input class="input100" type="password" name="password1" placeholder="Введите ваш пароль">
						<span class="focus-input100" data-symbol="&#xf190;"></span>
					</div>

					{% if errors.password1%}
						<span class="txt1">
						  {{errors.password1}}
						</span>
					{% endif %}

					<div class="wrap-input100 validate-input" data-validate="Password is required">
						<span class="label-input100">Пароль</span>
						<input class="input100" type="password" name="password2" placeholder="Повторите ваш пароль">
						<span class="focus-input100" data-symbol="&#xf190;"></span>
					</div>

					{% if errors.password2%}
						<span class="txt1">
						  {{errors.password2}}
						</span>
					{% endif %}

					<br>
					<div class="container-login100-form-btn">
						<div class="wrap-login100-form-btn">
							<div class="login100-form-bgbtn"></div>
							<button class="login100-form-btn">
								Зарегистрироваться
							</button>
						</div>
						{{error}}
					</div>
				</form>
				<div class="flex-col-c p-t-155">
					Уже есть аккаунт?
					<a href="{% url 'login:login_view' %}" class="txt2">
						Авторизироваться
					</a>
				</div>
			</div>
		</div>
	</div>
	

	<div id="dropDownSelect1"></div>
	
<!--===============================================================================================-->
	<script src="{% static 'login/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'login/vendor/animsition/js/animsition.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'login/vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'login/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'login/vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'login/vendor/daterangepicker/moment.min.js' %}"></script>
	<script src="{% static 'login/vendor/daterangepicker/daterangepicker.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'login/vendor/countdowntime/countdowntime.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'login/js/main.js' %}"></script>

</body>
</html>