cart/urls.py
# urls.py in store

from django.urls import path
from .views import cart_view, cart_add_view, cart_del_view, cart_buy_now_view, cart_remove_view

app_name = 'cart'

urlpatterns = [
    path('', cart_view, name="cart_view"),
    path('add/<str:id_product>', cart_add_view),
    path('del/<str:id_product>', cart_del_view),
    path('buy/<str:id_product>', cart_buy_now_view, name="buy_now"),
    path('remove/<str:id_product>', cart_remove_view, name="remove_now"),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from random import random
from django.http import HttpResponse
from app_datetime.views import datetime_view
from project.settings import DEBUG


def random_view(request):
    if request.method == "GET":
        data = random()
        return HttpResponse(data)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('random/', random_view),
    path('datetime/', datetime_view),
    path('weather/', include('app_weather.urls')),
    path('', include('store.urls')),
    path('cart/', include('cart.urls')),
    path('login/', include('app_login.urls')),
    path('wishlist/', include('wishlist.urls')),
    path('auth/', include('social_django.urls', namespace='social')),
]

if DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

cart/models.py
from django.db import models
from django.contrib.auth.models import User
from store.models import Product


class Cart(models.Model):
    """Модель корзины"""
    customer = models.OneToOneField(User,
                                    related_name='cart',
                                    on_delete=models.CASCADE)  # Ссылка на пользователя (у пользователя может быть только одна корзина)
    created_at = models.DateTimeField(auto_now_add=True)  # Дата и время создания объекта сущности в базе данных
    updated_at = models.DateTimeField(auto_now=True)  # Дата и время обновления объекта сущности в базе данных

    def __str__(self):
        return f"Корзина пользователя: {self.customer.username}"


class CartItem(models.Model):
    """Модель позиций в корзине"""
    cart = models.ForeignKey(Cart,
                             related_name='items',
                             on_delete=models.CASCADE)  # Ссылка на корзину
    product = models.ForeignKey(Product,
                                related_name='cart_items',
                                on_delete=models.CASCADE)  # Ссылка на продукт
    quantity = models.PositiveIntegerField(default=1)  # Число товаров в позиции заказа
    created_at = models.DateTimeField(auto_now_add=True)  # Дата и время создания объекта сущности в базе данных
    updated_at = models.DateTimeField(auto_now=True)  # Дата и время обновления объекта сущности в базе данных

    def __str__(self):
        return f"{self.product.name} - {self.quantity}"

cart/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse, HttpResponse, HttpResponseNotFound
from store.models import DATABASE
from logic.services import filtering_category, view_in_cart, add_to_cart, remove_from_cart
from django.contrib.auth import get_user
from django.contrib.auth.decorators import login_required
from .models import Cart, CartItem
from store.models import Product
from django.db.models import ExpressionWrapper, F, DecimalField, Case, When, Value



@login_required(login_url='login:login_view')
def cart_view(request):
    if request.method == "GET":
        cart = Cart.objects.get(customer=request.user)

        # При помощи select_related подгружаем дополнительные таблицы в одном запросе,
        # чтобы уменьшить число запросов
        products = cart.items.select_related(
            'product',
            'product__discount',
            'product__image').all()  # Список продуктов
        # Проводим аннотацию, чтобы собрать нужные значения в products
        products = products.annotate(
            price_after=Case(
                When(product__discount__isnull=False,
                     then=ExpressionWrapper(
                         F("product__price") * (100 - F(
                             "product__discount__value")) / 100,
                         output_field=DecimalField()
                     )),
                default=F("product__price"),  # Если скидки нет, использовать обычную цену
            ),  # Case - оператор выбора при условии When, если нет подходящих условий,
            # то возвращается default
            price_total=ExpressionWrapper(
                F("quantity") * F("price_after"),
                output_field=DecimalField()),
            name=F("product__name"),
            description=F("product__description"),
            url=F("product__image"),
        ).values("id", "quantity", "price_after", "price_total", "name", "description", "url")
        # values аналогично SELECT позволяет в запросе указать на вывод только те колонки, что необходимы
        return render(request, "cart/cart.html", context={"products": products})


@login_required(login_url='login:login_view')
def cart_buy_now_view(request, id_product):
    if request.method == "GET":
        cart = Cart.objects.get(customer=request.user)  # Получили корзину по пользователю
        product = Product.objects.get(id=id_product)  # Получили продукт по его id
        products_cart = cart.items.filter(product=product)
        if products_cart:
            cart_item = products_cart.first()
            cart_item.quantity += 1
            cart_item.save()
        else:
            CartItem.objects.create(cart=cart, product=product)  # Создали объект в CartItem по данным
        return redirect("cart:cart_view")

        return HttpResponseNotFound("Неудачное добавление в корзину")


def cart_remove_view(request, id_product):
    # id_product - неудачное название, так как на самом деле передаётся id_cart_item
    # тоесть номер строки в базе данных CartItem, поэтому при удалении получаем объект по его id и удаляем
    if request.method == "GET":
        cart_item = CartItem.objects.get(id=id_product)  # получаем объект по его id
        if cart_item:
            cart_item.delete()  # удаляем объект из БД
            return redirect("cart:cart_view")
        return HttpResponseNotFound("Неудачное удаление из корзины")


@login_required(login_url='login:login_view')
def cart_add_view(request, id_product):
    # Реализация для добавления в корзину, при нажатии на + на главной странице
    # (когда возвращается JSON, а не html)
    if request.method == "GET":
        cart = Cart.objects.get(customer=request.user)
        product = Product.objects.get(id=id_product)
        products_cart = cart.items.filter(product=product)
        if products_cart:
            cart_item = products_cart.first()
            cart_item.quantity += 1
            cart_item.save()
        else:
            CartItem.objects.create(cart=cart, product=product)  # Создали объект в CartItem по данным
        return JsonResponse(
            {"answer": "Продукт успешно добавлен в корзину"},
            json_dumps_params={'ensure_ascii': False})

        return JsonResponse({"answer": "Неудачное добавление в корзину"},
                            status=404,
                            json_dumps_params={'ensure_ascii': False})


def cart_del_view(request, id_product):
    def cart_del_view(request, id_product):
        # Реализация для удаления из корзины с возвращением JSON, а не html
        if request.method == "GET":
            cart_item = CartItem.objects.get(id=id_product)
            if cart_item:
                cart_item.delete()
                return JsonResponse({"answer": "Продукт успешно удалён из корзины"},
                                    json_dumps_params={'ensure_ascii': False})

            return JsonResponse({"answer": "Неудачное удаление из корзины"},
                                status=404,
                                json_dumps_params={'ensure_ascii': False})

cart/templates/cart/cart.html
{% extends 'store/base.html' %}
{%load static%}

{% block title %} <!-- Блок для названия страницы-->
<title>Корзина</title>
{% endblock %}

{% block content %} <!-- Блок для уникального содержимого страницы-->
<div class="hero-wrap hero-bread" style="background-image: url({% static 'store/images/bg_1.jpg' %});">
  <div class="container">
	<div class="row no-gutters slider-text align-items-center justify-content-center">
	  <div class="col-md-9 ftco-animate text-center">
		<p class="breadcrumbs"><span class="mr-2"></span></p>
		<h1 class="mb-0 bread">Корзина</h1>
	  </div>
	</div>
  </div>
</div>

<section class="ftco-section ftco-cart">
		<div class="container">
			<div class="row">
			<div class="col-md-12 ftco-animate">
				<div class="cart-list">
					<table class="table">
						<thead class="thead-primary">
						  <tr class="text-center">
							<th>&nbsp;</th>
							<th>&nbsp;</th>
							<th>Продукт</th>
							<th>Цена, &#x20bd</th>
							<th>Количество товара</th>
							<th>Общая цена, &#x20bd</th>
						  </tr>
						</thead>
						<tbody>
						  {% for product in products %}
						  <tr class="text-center">
							<td class="product-remove"><a href="{% url 'cart:remove_now' product.id %}"><span class="ion-ios-close"></span></a></td>

							<td class="image-prod"><div class="img" style="background-image:url(/{{ product.url }});"></div></td>

							<td class="product-name">
								<h3>{{product.name}}</h3>
								<p>{{product.description}}</p>
							</td>

							<td class="price">{{product.price_after}}</td>

							<td class="quantity">
								<div class="input-group mb-3">
								<input type="number" name="quantity" class="quantity form-control input-number" value={{product.quantity}} min="1" max="100">
							</div>
						  </td>

							<td class="total">{{product.price_total}}</td>
						  </tr><!-- END TR-->
						  {% endfor %}
						</tbody>
					  </table>
				  </div>
			</div>
		</div>
		<div class="row justify-content-end">
			<div class="col-lg-4 mt-5 cart-wrap ftco-animate">
				<div class="cart-total mb-3">
					<h3>Промокод</h3>
					<p>Введите код купона, если он у вас есть</p>
					<form action="#" class="info">
					  <div class="form-group">
						<input type="text" id='promo-input' class="form-control text-left px-3" placeholder="Промокод">
					  </div>
					</form>
				</div>
				<p><button id="checkCoupon" class="btn btn-primary py-3 px-4">Применить промокод</button></p>
				<div id="couponResult"></div>
			</div>
			<div class="col-lg-4 mt-5 cart-wrap ftco-animate">
				<div class="cart-total mb-3">
					<h3>Расчёт доставки</h3>
					<p>Введите ваш город доставки</p>
					<form action="#" class="info">
					  <div class="form-group">
						<label>Страна</label>
						<input type="text" id='delivery-country' class="form-control text-left px-3" placeholder="Россия" required>
					  </div>
					  <div class="form-group">
						<label>Город/Населенный пункт</label>
						<input type="text" id='delivery-city' class="form-control text-left px-3" placeholder="Санкт-Петербург" required>
					  </div>
					  <div class="form-group">
						<label>Почтовый код</label>
						<input type="text" id='delivery-post-code' class="form-control text-left px-3" placeholder="195251" required>
					  </div>

					</form>
				</div>
					<p><button id="estimateDelivery" class="btn btn-primary py-3 px-4">Рассчитать</button></p>
					<div id="estimateResult"></div>
			</div>
			<div class="col-lg-4 mt-5 cart-wrap ftco-animate">
				<div class="cart-total mb-3">
					<h3>Стоимость покупку</h3>
					<p class="d-flex">
						<span>Промежуточный итог</span>
						&#x20bd  <span id="subtotal-value">710.00</span>
					</p>
					<p class="d-flex">
						<span>Доставка</span>
						&#x20bd <span id="delivery-value">0.00</span>
					</p>
					<p class="d-flex">
						<span>Скидки</span>
						&#x20bd <span id="discount-value">0.00</span>
					</p>
					<hr>
					<p class="d-flex total-price">
						<span>Итог</span>
						<b style="color: black">&#x20bd</b> <span id="total-value">710.00</span>
					</p>
				</div>
				<p><a href="checkout.html" class="btn btn-primary py-3 px-4">Оплатить</a></p>
			</div>
		</div>
		</div>
	</section>
{% endblock %}

{% block custom_scripts %} <!-- Блок для загрузки дополнительного кода встроенного в html-->
<script>
	// Получаем элементы с значениями
	let subtotalElement = document.getElementById('subtotal-value');
	let deliveryElement = document.getElementById('delivery-value');
	let discountElement = document.getElementById('discount-value');
	let totalElement = document.getElementById('total-value');

	// Функция для обновления итога
	function updateTotal() {
		// Получаем значения промежуточного итога, доставки и скидок из элементов
		let subtotal = parseFloat(subtotalElement.textContent);
		let delivery = parseFloat(deliveryElement.textContent);
		let discount = parseFloat(discountElement.textContent);

		// Вычисляем итог
		let total = subtotal + delivery - discount;

		// Убеждаемся, что итог не становится отрицательным
		if (total < 0) {
			total = 0;
		}

		// Обновляем элемент с итогом
		totalElement.textContent = total.toFixed(2);
	}

	// Вызываем функцию для первичного расчета итога
	updateTotal();
</script>

<script>
	// Получаем все элементы с классами "quantity" и "total"
	let quantityInputs = document.querySelectorAll('.quantity input');
	let totalElements = document.querySelectorAll('.total');
	let priceElements = document.querySelectorAll('.price');
	// Функция для обновления промежуточного итога
	function updateSubtotal() {
		// Инициализируем переменные для промежуточного итога и цены товара
		let subtotal = 0;

		// Проходимся по всем элементам с классом "quantity"
		quantityInputs.forEach(function(input, index) {
			// Получаем значение количества товара
			let quantity = parseInt(input.value, 10);

			// Получаем цену товара из HTML (хотя обычно идёт запрос на сервер)
			let price = parseFloat(priceElements[index].textContent);

			// Рассчитываем общую цену для данной позиции
			let itemTotal = quantity * price;

			// Обновляем элемент с классом "total" для данной позиции
			totalElements[index].textContent = itemTotal.toFixed(2);

			// Добавляем общую цену данной позиции к общему промежуточному итогу
			subtotal += itemTotal;
		});

		// Обновляем элемент с итогом
		document.getElementById('subtotal-value').textContent = subtotal.toFixed(2); // Форматируем итог в нужный вид

		updateTotal(); // Вызываем пересчёт корзины
		// document.querySelector('.total-price span:last-child').textContent = '₽ ' + subtotal.toFixed(2); // Форматируем итог в нужный вид
	}

	// Слушаем событие изменения ввода количества товара
	quantityInputs.forEach(function(input) {
		input.addEventListener('change', updateSubtotal);
	});

	// Вызываем функцию для первичного расчета итога
	updateSubtotal();
	</script>

<script>
	// Проверка действия купона

	let promoElement = document.getElementById('promo-input');
	let checkCouponButton = document.getElementById('checkCoupon');
	let subtotal_with_discount = 0;
	// Функция для проверки действия купона
	function checkCoupon() {
		// Получаем значение купона, которое вы хотите проверить
		let couponCode = promoElement.value;

		console.log(couponCode);

		// Делаем кнопку неактивной, чтобы предотвратить повторные запросы
		checkCouponButton.disabled = true;

		// Отправляем асинхронный GET-запрос на сервер для проверки купона
		fetch('/coupon/check/' + couponCode, {
			method: 'GET'
		})
		.then(function(response) {
			// Проверяем статус ответа
			if (!response.ok) {
				throw new Error('Ошибка при проверке купона');
			}
			return response.json();
		})
		.then(function(data) {
			// Обрабатываем данные, которые пришли с сервера
			if (data.is_valid) {
				document.getElementById('couponResult').textContent = 'Купон действителен! Размер скидки: ' + data.discount + '%';
				subtotal_with_discount = parseFloat(subtotalElement.textContent) * 0.01 * data.discount;
				discountElement.textContent = subtotal_with_discount.toFixed(2);
				updateTotal();
			} else {
				document.getElementById('couponResult').textContent = 'Купон не действителен!';
			}
		})
		.catch(function(error) {
			// Обрабатываем ошибку
			console.error(error);
			document.getElementById('couponResult').textContent = 'Произошла ошибка при проверке купона';
		})
		.finally(function() {
			// Включаем кнопку обратно после получения ответа (успешного или с ошибкой)
			checkCouponButton.disabled = false;
		});
	};

	checkCouponButton.addEventListener('click', checkCoupon);
</script>

<script>
	// Расчёт стоимости доставки

	let deliveryCountry = document.getElementById('delivery-country');
	let deliveryCity = document.getElementById('delivery-city');
	let deliveryCode = document.getElementById('delivery-post-code');
	let estimateButton = document.getElementById('estimateDelivery');
	// let deliveryElement = document.getElementById('delivery-value');
	// Функция для расчёта стоимости доставки
	function estimateDelivery() {
		// Получаем значение купона, которое вы хотите проверить
		let country = deliveryCountry.value;
		let city = deliveryCity.value;
		let code = deliveryCode.value;

		console.log(country, city, code);

		// Делаем кнопку неактивной, чтобы предотвратить повторные запросы
		estimateButton.disabled = true;

		// Отправляем асинхронный GET-запрос на сервер для расчёта стоимости доставки
		fetch('/delivery/estimate?country=' + country + '&city=' + city + '&code=' + code, {
			method: 'GET'
		})
		.then(function(response) {
			// Проверяем статус ответа
			if (!response.ok) {
				throw new Error('Ошибка при проверке купона');
			}
			return response.json();
		})
		.then(function(data) {
			// Обрабатываем данные, которые пришли с сервера
			deliveryElement.textContent = data.price.toFixed(2);
			document.getElementById('estimateResult').textContent = 'Доставка рассчитана и внесена в стоимость заказа';
			updateTotal();
		})
		.catch(function(error) {
			// Обрабатываем ошибку
			console.error(error);
			document.getElementById('estimateResult').textContent = 'Сюда, к сожалению, не доставляем';
		})
		.finally(function() {
			// Включаем кнопку обратно после получения ответа (успешного или с ошибкой)
			estimateButton.disabled = false;
		});
	};

	estimateButton.addEventListener('click', estimateDelivery);
</script>
{% endblock %}