cart/urls.py
# urls.py in store

from django.urls import path
from .views import cart_view, cart_add_view, cart_del_view, cart_buy_now_view, cart_remove_view

app_name = 'cart'

urlpatterns = [
    path('', cart_view, name="cart_view"),
    path('add/<str:id_product>', cart_add_view),
    path('del/<str:id_product>', cart_del_view),
    path('buy/<str:id_product>', cart_buy_now_view, name="buy_now"),
    path('remove/<str:id_product>', cart_remove_view, name="remove_now"),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from random import random
from django.http import HttpResponse
from app_datetime.views import datetime_view
from project.settings import DEBUG


def random_view(request):
    if request.method == "GET":
        data = random()
        return HttpResponse(data)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('random/', random_view),
    path('datetime/', datetime_view),
    path('weather/', include('app_weather.urls')),
    path('', include('store.urls')),
    path('cart/', include('cart.urls')),
    path('login/', include('app_login.urls')),
    path('wishlist/', include('wishlist.urls')),
    path('auth/', include('social_django.urls', namespace='social')),
]

if DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

store/urls.py
# urls.py in store

from django.urls import path
from .views import products_view, shop_view, products_page_view, coupon_check_view, delivery_estimate_view

app_name = 'store'

urlpatterns = [
    path('product/', products_view),
    path('', shop_view, name="shop_view"),
    path('product/<slug:page>.html', products_page_view, name="products_page_view"),
    path('product/<int:page>', products_page_view),

    path('coupon/check/<slug:name_coupon>', coupon_check_view),
    path('delivery/estimate/', delivery_estimate_view),
]

wishlist/urls.py
from django.urls import path
from .views import wishlist_view, wishlist_add_json, wishlist_del_json, wishlist_del_view, wishlist_json

app_name = 'wishlist'

urlpatterns = [
    path('', wishlist_view, name='wishlist_view'),
    path('api/add/<str:id_product>', wishlist_add_json),
    path('api/del/<str:id_product>', wishlist_del_json),
    path('api/', wishlist_json),
    path('del/<str:id_product>', wishlist_del_view, name="wishlist_del_view"),
]

wishlist/models.py
from django.db import models

# Create your models here.

wishlist/views.py
from django.shortcuts import render, redirect
from logic.services import view_in_wishlist, add_to_wishlist, remove_from_wishlist
from store.models import DATABASE
from django.contrib.auth import get_user
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse, HttpResponse


@login_required(login_url='login:login_view')
def wishlist_view(request):
    if request.method == "GET":
        current_user = get_user(request).username
        data = view_in_wishlist(request).get(current_user)

        products = []  # Список продуктов
        for product_id in data['products']:
            product = DATABASE.get(product_id)
            products.append(product)

        return render(request, 'wishlist/wishlist.html', context={"products": products})


def wishlist_add_json(request, id_product):
    if request.method == "GET":
        result = add_to_wishlist(request, id_product)
        if result:
            return JsonResponse({"answer": "Продукт успешно добавлен в избранное"},
                                json_dumps_params={'ensure_ascii': False})

        return JsonResponse({"answer": "Неудачное добавление в избранное"},
                            status=404,
                            json_dumps_params={'ensure_ascii': False})


def wishlist_del_json(request, id_product):
    if request.method == "GET":
        result = remove_from_wishlist(request, id_product)
        if result:
            return JsonResponse({"answer": "Продукт успешно удалён из корзины"},
                                json_dumps_params={'ensure_ascii': False})

        return JsonResponse({"answer": "Неудачное удаление из корзины"},
                            status=404,
                            json_dumps_params={'ensure_ascii': False})


def wishlist_json(request):
    if request.method == "GET":
        current_user = get_user(request).username
        data = view_in_wishlist(request).get(current_user)
        if data:
            return JsonResponse(data,
                                json_dumps_params={'ensure_ascii': False})
        return JsonResponse({"answer": "Пользователь не авторизирован"},
                            json_dumps_params={'ensure_ascii': False},
                            status=404)


def wishlist_del_view(request, id_product):
    if request.method == "GET":
        result = remove_from_wishlist(request, id_product)
        if result:
            return redirect("wishlist:wishlist_view")

        return HttpResponse("Неудачное удаление из корзины", status=404)

wishlist/templates/wishlist/wishlist.html
{% extends 'store/base.html' %}
{%load static%}

{% block title %} <!-- Блок для названия страницы-->
<title>Избранное</title>
{% endblock %}

{% block content %} <!-- Блок для уникального содержимого страницы-->
    <div class="hero-wrap hero-bread" style="background-image: url({% static 'store/images/bg_1.jpg' %});">
      <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
          <div class="col-md-9 ftco-animate text-center">
          	<p class="breadcrumbs"><span class="mr-2"></span></p>
            <h1 class="mb-0 bread">Избранное</h1>
          </div>
        </div>
      </div>
    </div>

    <section class="ftco-section ftco-cart">
			<div class="container">
				<div class="row">
    			<div class="col-md-12 ftco-animate">
    				<div class="cart-list">
	    				<table class="table">
						    <thead class="thead-primary">
						      <tr class="text-center">
						        <th></th>
						        <th></th>
						        <th>Продукт</th>
						        <th>Цена, &#x20bd</th>
						      </tr>
						    </thead>
						    <tbody>
						    {% for product in products %}
							<tr class="text-center">
						        <td class="product-remove"><a href="{% url 'wishlist:wishlist_del_view' product.id %}"><span class="ion-ios-close"></span></a></td>
						        
						        <td class="image-prod"><a href="{% url 'store:products_page_view' product.html %}">
									<div class="img" style="background-image:url({% static product.url %});"></div>
								</a></td>
						        
						        <td class="product-name">
						        	<h3>{{product.name}}</h3>
						        	<p>{{product.description}}</p>
						        </td>
						        {% if product.discount %}
						        <td class="price"><del>{{product.price_before}}</del> {{product.price_after}}</td>
								{% else %}
								<td class="price">{{product.price_before}}</td>
								{% endif %}
						      </tr><!-- END TR-->
							{% endfor %}
						    </tbody>
						  </table>
					  </div>
    			</div>
    		</div>
			</div>
		</section>

{% endblock %}